homework/homework/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^myapp/',include('myapp.urls',namespace='app'))
]

homework/myapp/urls.py
from django.conf.urls import url

from myapp import views

urlpatterns = [
    # 添加
    url(r'^addgrades/$',views.addgrades),
    url(r'^addstudents/$',views.addstudent),
    url(r'^addstusuccess/$',views.addstusuccess),
    url(r'^addgradessuccess/$',views.addgradessuccess),
    # 显示信息
    url(r'^students/$',views.students,name='students'),
    url(r'^grades/$',views.grades,name='grades'),
    url(r'^pagestu/(\d+)/$',views.pagestu),
    # 用来html中的a标签的跳转使用
    url(r'^grades/(\w+)/$',views.gradestudents),
    url(r'^students/(\w+)/$', views.studentsgrades),
#     删除学生
    url(r'^deletestudent/$',views.deletestu,name='del'),
    url(r'^deletestudentsuccess/$', views.deletestusuccess,name='deletesuccess')
]

homework/myapp/models.py
from django.db import models

# Create your models here.
class myManager(models.Manager):
    def get_queryset(self):
        # 过滤出来没有删除的
        return super(myManager, self).get_queryset().filter(isdelete=False)



# 班级信息表
class Grades(models.Model):
    g_name = models.CharField(max_length=20,unique=True)
    g_date = models.DateField(default='2018-01-24')
    g_num = models.IntegerField(default=0)
    isdelete = models.BooleanField(default=False)
    def __str__(self):
        return self.g_name
    # 设置表的名称及排序
    # 元选项
    class Meta():
        db_table = 'grades'
        # ordering = ['id']
    objects = myManager()
# 学生信息表
class Students(models.Model):
    s_name = models.CharField(max_length=20)
    s_age = models.IntegerField()
    s_gender = models.BooleanField()
    isdelete = models.BooleanField(default=False)
    # 这里使用的是外键
    s_grade = models.ForeignKey(Grades)
    objects = myManager()
    def __str__(self):
        return self.s_name
    # 对于布尔类型的性别进行转变成中文
    def gender(self):
        if self.s_gender:
            return '男'
        else:
            return '女'

    class Meta():
        db_table = 'students'
        # ordering = ['s_age']

homework/myapp/views.py
import random

from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from myapp.models import Grades, Students


# 添加班级
# def addgrades(request):
#     grade = Grades()
#     num = random.randrange(1, 20)
#     grade.g_name = 'python{}'.format(num)
#     grade.g_num = num
#     grade.save()
#     return HttpResponse('添加班级成功%d' % num)
def addgrades(request):
    return render(request, 'addgrades.html')


def addgradessuccess(request):
    grade = Grades()
    grade.g_name = request.POST['g_name']
    grade.g_num = request.POST['g_num']
    grade.g_date = request.POST['g_date']
    grade.save()
    return HttpResponse('添加班级成功{}'.format(request.POST['g_name']))


# 添加学生
# def addstudent(request):
#     stu = Students()
#     num = random.randrange(1,40)
#     stu.s_name = 'tom{}'.format(num)
#     stu.s_age = num
#     # 获取到最后一个班级赋值给新生成的学生
#     stu.s_grade = Grades.objects.first()
#     stu.s_gender = False
#     # 数据的修改必须要save才能够提交上
#     stu.save()
#     return HttpResponse('添加学生成功%d'%num)

def addstudent(request):
    return render(request, 'addstudents.html')


def addstusuccess(request):
    stu = Students()
    stu.s_name = request.POST['s_name']
    stu.s_age = request.POST['s_age']
    s_gender = request.POST['s_gender']
    if s_gender == '男':
        s_gender = True
    else:
        s_gender = False
    stu.s_gender = s_gender
    name = request.POST['s_grade']
    # print(g_name)
    # 过滤出来名字相同的班级
    grades = Grades.objects.all().filter(g_name=name)
    if grades:
        # 获取到这个名字相同的班级
        grade = Grades.objects.get(g_name=name)
        # 必须要将班级的id与学生的外键相关联，
        stu.s_grade_id = grade.id
        grade.g_num += 1
        grade.save()
    else:
        # 不存在这个班级就新建一个班级
        grade = Grades()
        g = Grades.objects.last()
        grade.g_name = name
        stu.s_grade_id = 1 + g.id
        grade.g_num = 1
        grade.save()
    stu.save()
    return HttpResponse('添加学生成功%s' % request.POST['s_name'])


# 展示学生信息
def students(request):
    # 获取所有的数据
    students = Students.objects.all()
    # pageinator = Paginator(students,5)
    # page = pageinator.page(pageid)
    data = {'students': students}
    return render(request, 'students.html', data)


# 展示班级信息
def grades(request):
    grades = Grades.objects.all()
    data = {'grades': grades}
    return render(request, 'grades.html', data)


# 班级信息里点击班级可以显示班级的学生信息
def gradestudents(request, name):
    grade = Grades.objects.get(g_name=name)
    # 获取关联对象的集合
    stulist = grade.students_set.all()
    return render(request, 'students.html', {'students': stulist})


# 在学生信息页面中单击班级显示该班级的信息
def studentsgrades(request, name):
    grade = Grades.objects.get(g_name=name)
    # print(num)
    # 获取关联对象的集合
    stulist = grade.students_set.all()
    return render(request, 'students.html', {'students': stulist})


# def gs(request,num1,num2):
#     grade = Grades.objects.get(pk=num2)
#     stulist = grade.students_set.all()
#     return render(request, 'students.html', {'students': stulist})


def deletestu(request):
    return render(request, 'deletestu.html')


def deletestusuccess(request):
    name = request.POST['name']
    print(name)
    stu = Students.objects.get(s_name=name)
    stu.isdelete = True
    stu.save()
    print(123123)
    return render(request, 'deletestusuccess.html', {'stu': stu})


def pagestu(request,pageid):
    # 获取所有的数据
    # print(pageid)
    allList = Students.objects.all()
    pageinator = Paginator(allList,5)
    page = pageinator.page(pageid)
    data = {'students': page}
    return render(request, 'pagestu.html', data)

homework/templates/addgrades.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加班级</title>
</head>
<body>
<h1>添加班级信息</h1>
<form action="/myapp/addgradessuccess/"method="post">
    {% csrf_token %}
    班级名称：<input type="text"name="g_name"><br/>
    班级创建时间：<input type="date"name="g_date"><br/>
    班级人数：<input type="number"name="g_num"><br/>
    <br/>
    <input type="submit" value="提交">
</form>
</body>
</html>

homework/templates/addstudents.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加学生</title>
</head>
<body>
<h1>添加学生</h1>
<form action="/myapp/addstusuccess/"method="post">
    {% csrf_token %}
    姓名：<input type="text"name="s_name"><br/>
    年龄：<input type="number"name="s_age"><br/>
    性别：<input type="radio"name="s_gender"checked="checked">男
    <input type="radio"name="s_gender">女<br/>
    班级：<input type="text"name="s_grade"><br/>
    <br/>
    <input type="submit" value="提交">
</form>

</body>
</html>

homework/templates/deletestu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>删除学生</title>
</head>
<body>
<h1>删除学生</h1>
<form action="/myapp/deletestudentsuccess/"method="post">
    {% csrf_token %}
{#    要删除的学生姓名: <select name="s_name" >#}
{#                {% for student in students %}#}
{#                    <option value="{{ student.s_name }}">{{ student.s_name }}</option>#}
{#                {% endfor %}#}
{#            </select>#}
    要删除的学生姓名:
    <input type="text" name="name"><br/>
    <input type="submit" value="提交">

</form>
</body>
</html>

homework/templates/deletestusuccess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h5>删除成功，您删除的学生信息如下：</h5><br/>
    {{ stu.s_name }}--{{ stu.s_age }}--{{ stu.gender }}--{{ stu.s_grade }}
</body>
</html>

homework/templates/grades.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>grades</title>
</head>
<body>
<h1>班级信息</h1>
<table border="1" style="background: greenyellow">
    <thead>
            <th>班级</th>
            <th>数量</th>
            <th>成立日期</th>
    </thead>
    <tbody>
          {% for grade in grades %}
              <tr>
                  <td><a href={{ grade.g_name }}>{{ grade.g_name }}</a></td>
               <td>{{ grade.g_num }}</td>
               <td>{{ grade.g_date }}</td>
              </tr>
      {% endfor %}
    </tbody>

</table>


</body>
</html>

homework/templates/pagestu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table border="1" style="background: greenyellow">
    <thead>
    <th>姓名</th>
    <th>性别</th>
    <th>年龄</th>
    <th>班级</th>
    </thead>
    <tbody>
    {% for student in students %}

        {#        {% if student.isdelete %}#}
        {#            <tr>该学生已删除</tr>#}
        {#        {% else %}#}
        {#        {% for index in students.paginator.page_range %}#}
        <tr>
            <td>{{ student.s_name }}</td>
            <td>{{ student.gender }}</td>
            <td>{{ student.s_age }}</td>
            <td><a href={{ student.s_grade.g_name }}>{{ student.s_grade }}</a></td>
        </tr>
    {% empty %}
        <h2>现在还没有学生</h2>
    {% endfor %}
    </tbody>

</table>
<ul>
{% for index in students.paginator.page_range %}
    {% if index == students.number %}
        <li>{{ index }}</li>
    {% else %}
        <li>
            <a href="/myapp/pagestu/{{ index }}/">{{ index }}</a>
        </li>
    {% endif %}
{% endfor %}
</ul>
</body>
</html>

homework/templates/students.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>students</title>
</head>
<body>
<h1>学生信息</h1>
<table border="1" style="background: greenyellow">
    <thead>
    <th>姓名</th>
    <th>性别</th>
    <th>年龄</th>
    <th>班级</th>
    <th>删除</th>
    </thead>
    <tbody>
    {% for student in students %}

        {#        {% if student.isdelete %}#}
        {#            <tr>该学生已删除</tr>#}
        {#        {% else %}#}
        {#        {% for index in students.paginator.page_range %}#}
        <tr>
            <td>{{ student.s_name }}</td>
            <td>{{ student.gender }}</td>
            <td>{{ student.s_age }}</td>
            <td><a href={{ student.s_grade.g_name }}>{{ student.s_grade }}</a></td>
            <td><a href={% url 'app:del' %}>删除</a></td>
        </tr>
    {% empty %}
        <h2>现在还没有学生</h2>
    {% endfor %}
    </tbody>

</table>


</body>
</html>